# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ANSIBLE_DIR = "../ansible"
K3S_PLAYBOOK = "k3s.yaml"
DOCKER_PLAYBOOK = "docker.yaml"
NODE_IP = "192.168.56.101"

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.hostname = "subfluent"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "almalinux/10"
  config.vm.box_version = "10.2.20260914"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: NODE_IP

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  config.vm.synced_folder ".", "/vagrant", disabled: false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "subfluent"
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  
    vb.cpus = 2
    # Customize the amount of memory on the VM:
    vb.memory = 4096
  end
  
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  #
  # Run Ansible from the Vagrant Host

  playbook = ENV.fetch("PLAYBOOK", DOCKER_PLAYBOOK)

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "#{ANSIBLE_DIR}/#{playbook}"
    ansible.config_file = "../../ansible.cfg"

    ansible.groups = {
      "subfluent" => ["default"],
    }

    if playbook == K3S_PLAYBOOK
      ansible.groups["server"] = ["default"]
      ansible.groups["k3s_cluster:children"] = ["server"]

      ansible.extra_vars = {
        k3s_version: "v1.37.0+k3s1",
        api_endpoint: NODE_IP,
        # Required for vagrant ansible provisioner
        token: "vagrant",
        # Required to use the private network configured above
        extra_server_args: "--node-external-ip #{NODE_IP} --flannel-iface eth1",
      }
    end
  end
end
